<?php

// Single source of truth for car data used by product pages, homepage cards,
// and the car-type selects on the simulation / test-drive forms.
// NOTE: contact info for the site lives in config/site.php.

return [

    /*
     | Ordered spec groups shared by every car. Each car's 'specs' array
     | holds 48 values in exactly this order.
     */
    'spec_groups' => [
        'Performa' => [
            'Jenis Bahan Bakar',
            'Tenaga',
            'RPM At Max Power',
            'Kapasitas Mesin',
            'Torsi',
            'RPM At Max Torque',
        ],
        'Kapasitas' => [
            'Kapasitas Bagasi',
            'Ruang Kepala Depan',
            'Ruang Kepala Belakang',
            'Middle Row Legroom',
            'Berat Bersih',
            'Panjang',
            'Tinggi',
            'Jumlah Pintu',
            'Kapasitas Tangki Bahan Bakar',
            'Berat Kotor',
            'Lebar',
            'Jarak Sumbu Roda',
            'Kapasitas Tempat duduk',
        ],
        'Transmisi' => [
            'Jenis Transmisi',
            'Jenis Penggerak',
            'Girboks',
            'Steering Wheel Gearshift Paddle',
        ],
        'Suspensi & Rem' => [
            'Jenis Rem Depan',
            'Suspensi Depan',
            'Jenis Rem Belakang',
            'Suspensi Belakang',
        ],
        'Detil Mesin' => [
            'Mesin',
            'Sistem Suplai Bahan Bakar',
            'Jumlah Silinder',
            'Katup per Silinder',
            'Tipe Baterai',
            'Regenerative Braking',
            'Tipe Penggerak Listrik',
            'Kapasitas Baterai',
            'AC charging (0-100%)',
            'Emission',
        ],
        'Velg & Ban' => [
            'Velg alloy',
            'Ukuran Velg Alloy',
            'Jenis Ban',
            'Cover Velg',
            'Ukuran Ban',
            'Ukuran Velg',
        ],
        'Kemudi' => [
            'Power Steering',
            'Pengaturan Posisi Stir',
            'Kolom Kemudi',
            'Jenis Kemudi',
            'Steering Gear Type',
        ],
    ],

    'cars' => [
        'stargazer' => [
            'name'       => 'HYUNDAI STARGAZER',
            'title'      => 'HYUNDAI STARGAZER - Dealer Hyundai Makassar',
            'slug'       => 'stargazer',
            'price'      => 'Rp249.600.000',
            'image'      => 'images/car/Hyundai-Stargazer.png',
            'categories' => ['mpv'],
            'folder'     => 'hyundai-stargazer',
            'slides'     => 6,
            'benefit'    => 'Keuntungan membeli HYUNDAI STARGAZER di Hyundai Makassar',
            'brochure'   => 'HYUNDAI STARGAZER',
            'video'      => [
                'heading' => 'Video HYUNDAI STARGAZER',
                'url'     => 'https://www.youtube.com/embed/Ap2um9HvDNQ',
                'caption' => 'Hyundai STARGAZER - Bintang Baru Keluarga',
            ],
            'specs'      => [
                'Bensin',
                '113 hp',
                '6300 RPM',
                '1497 cc',
                '144 Nm',
                '4500 RPM',
                '585 L',
                '1056 mm',
                '961 mm',
                '1014 mm',
                '1191 kg',
                '4460 mm',
                '1695 mm',
                '5',
                '40 L',
                '1780 kg',
                '1780 mm',
                '2780 mm',
                '7 Kursi',
                'Manual',
                '',
                '6 - Speed',
                '',
                '',
                '',
                '',
                '',
                '1.5L Petrol Engine, 4 Cylinder 16 Valve DOHC',
                'MPI',
                '4',
                '4',
                '',
                '',
                '',
                '',
                '',
                '',
                'Ya',
                '15 Inch',
                'Radial',
                'Tidak',
                '185/65 R15',
                'R15',
                'Ya',
                'Ya',
                'Adjustable',
                'Power',
                'Rack & Pinion',
            ],
        ],

        'creta' => [
            'name'       => 'HYUNDAI CRETA',
            'title'      => 'HYUNDAI CRETA - Dealer Hyundai Makassar',
            'slug'       => 'creta',
            'price'      => 'Rp297.000.000',
            'image'      => 'images/car/Hyundai-Creta.png',
            'categories' => ['suv'],
            'folder'     => 'hyundai-creta',
            'slides'     => 6,
            'benefit'    => 'Keuntungan membeli HYUNDAI CRETA di Hyundai Makassar',
            'brochure'   => 'HYUNDAI CRETA',
            'video'      => [
                'heading' => 'Video HYUNDAI CRETA',
                'url'     => 'https://www.youtube.com/embed/FW0OBtFiJvI',
                'caption' => 'Hyundai CRETA | Spotlight in Motion',
            ],
            'specs'      => [
                'Bensin',
                '113 hp',
                '6300 RPM',
                '1497 cc',
                '144 Nm',
                '4500 RPM',
                '116 L',
                '1056 mm',
                '961 mm',
                '1014 mm',
                '1165 kg',
                '4315 mm',
                '1639 mm',
                '5',
                '40 L',
                '1590 kg',
                '1790 mm',
                '2610 mm',
                '5 Kursi',
                'Manual',
                '',
                '6 - Speed',
                'Tidak',
                'Ventilated Discs',
                'MacPherson Strut',
                'Drums',
                'Multi-Lin',
                '1.5L Petrol Engine, 4 Cylinder 16 Valve',
                'MPI',
                '4',
                '4',
                '',
                '',
                '',
                '',
                '',
                '',
                'Ya',
                '17 Inch',
                'Radial',
                'Tidak',
                '215/60 R17',
                'R17',
                'Ya',
                'Ya',
                'Tilt',
                'Power',
                'Rack & Pinion',
            ],
        ],

        'stargazer-x' => [
            'name'       => 'HYUNDAI STARGAZER X',
            'title'      => 'HYUNDAI STARGAZER X - Dealer Hyundai Makassar',
            'slug'       => 'stargazer-x',
            'price'      => 'Rp335.800.000',
            'image'      => 'images/car/Stargazer-X.png',
            'categories' => ['mpv'],
            'folder'     => 'hyundai-stargazer-x',
            'slides'     => 5,
            'benefit'    => 'Keuntungan membeli STARGAZER X di Hyundai Makassar',
            'brochure'   => 'HYUNDAI STARGAZER X',
            'video'      => [
                'heading' => 'Video HYUNDAI STARGAZER X',
                'url'     => 'https://www.youtube.com/embed/zbrALbCopKs',
                'caption' => 'STARGAZER X: Unleash the X in you',
            ],
            'specs'      => [
                'Bensin',
                '113 hp',
                '6300 RPM',
                '1497 cc',
                '144 Nm',
                '45000 RPM',
                '585 L',
                '1056 mm',
                '961 mm',
                '1014 mm',
                '1191 kg',
                '4460 mm',
                '1695 mm',
                '5',
                '40 L',
                '1780 kg',
                '1780 mm',
                '2780 mm',
                '7 Kursi',
                'Manual',
                '',
                '6 - Speed',
                '',
                'Ventilated Discs',
                'Double Wishbon',
                'Double Wishbon',
                'Torsion Beam',
                '1.5L Petrol Engine, 4 Cylinder 16 Valve',
                'MPI',
                '4',
                '4',
                '',
                '',
                '',
                '',
                '',
                '',
                'Ya',
                '15 Inch',
                'Radial',
                'Tidak',
                '185/65 R15',
                'R15',
                'Ya',
                'Ya',
                'Adjustable',
                'Power',
                'Rack & Pinion',
            ],
        ],

        'hyundai-kona' => [
            'name'       => 'HYUNDAI KONA ELECTRIC',
            'title'      => 'HYUNDAI KONA ELECTRIC - Dealer Hyundai Makassar',
            'slug'       => 'hyundai-kona',
            'price'      => 'Rp297.000.000',
            'image'      => 'images/car/Hyundai-Kona.png',
            'categories' => ['eco'],
            'folder'     => 'hyundai-kona',
            'slides'     => 5,
            'benefit'    => 'Keuntungan membeli HYUNDAI KONA ELECTRIC di Hyundai Makassar',
            'brochure'   => 'HYUNDAI KONA ELECTRIC',
            'video'      => [
                'heading' => 'Video HYUNDAI KONA ELECTRIC',
                'url'     => 'https://www.youtube.com/embed/6jp_2C6OIGY',
                'caption' => 'The all-new KONA | Product Review',
            ],
            'specs'      => [
                'Electric',
                '134 hp',
                '',
                '',
                '395 Nm',
                '',
                '',
                '',
                '',
                '',
                '',
                '4205 mm',
                '1570 mm',
                '5',
                '',
                '',
                '1800 mm',
                '2600 mm',
                '5 Kursi',
                'Otomatis',
                '',
                'Single Speed',
                '',
                'Ventilated Discs',
                'MacPherson Strut',
                'Discs',
                'Multi-Link',
                '',
                '',
                '',
                '',
                'Lithium-ion',
                '',
                '',
                '',
                '',
                '0 g/km',
                '',
                '',
                '',
                '',
                '',
                '',
                'Ya',
                'Ya',
                'Adjustable',
                'Power',
                'Rack & Pinion',
            ],
        ],

        'santa-fe' => [
            'name'       => 'HYUNDAI SANTA FE',
            'title'      => 'HYUNDAI SANTA FE - Dealer Hyundai Makassar',
            'slug'       => 'santa-fe',
            'price'      => 'Rp625.000.000',
            'image'      => 'images/car/Hyundai-Santa-Fe.png',
            'categories' => ['suv'],
            'folder'     => 'santa-fe',
            'slides'     => 5,
            'benefit'    => 'Keuntungan membeli HYUNDAI SANTA FE di Hyundai Makassar',
            'brochure'   => 'HYUNDAI SANTA FE',
            'video'      => [
                'heading' => 'Video HYUNDAI SANTA FE',
                'url'     => 'https://www.youtube.com/embed/TI6t8xMvGyU',
                'caption' => 'Journey to Love - New SANTA FE',
            ],
            'specs'      => [
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
            ],
        ],

        'ioniq-5' => [
            'name'       => 'HYUNDAI IONIQ 5',
            'title'      => 'HYUNDAI IONIQ 5 - Dealer Hyundai Makassar',
            'slug'       => 'ioniq-5',
            'price'      => 'Rp399.000.000',
            'image'      => 'images/car/Hyundai-Ioniq-5.png',
            'categories' => ['eco'],
            'folder'     => 'ioniq-5',
            'slides'     => 5,
            'benefit'    => 'Keuntungan membeli HYUNDAI IONIQ 5 di Hyundai Makassar',
            'brochure'   => 'HYUNDAI IONIQ 5',
            'video'      => [
                'heading' => 'Video HYUNDAI IONIQ 5',
                'url'     => 'https://www.youtube.com/embed/S8cThE8V398',
                'caption' => 'Power Up the Future with Hyundai IONIQ 5',
            ],
            'specs'      => [
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
            ],
        ],

        'all-new-santa-fe' => [
            'name'       => 'ALL NEW SANTA FE',
            'title'      => 'HYUNDAI ALL NEW SANTA FE - Dealer Hyundai Makassar',
            'slug'       => 'all-new-santa-fe',
            'price'      => 'Rp869.600.000',
            'image'      => 'images/car/ALL-NEW-SANTA.png',
            'categories' => ['suv'],
            'folder'     => 'all-new-santa-fe',
            'slides'     => 5,
            'benefit'    => 'Keuntungan membeli HYUNDAI ALL NEW SANTA FE di Hyundai Makassar',
            'brochure'   => 'ALL NEW SANTA FE',
            'video'      => [
                'heading' => 'Video HYUNDAI ALL NEW SANTA FE',
                'url'     => 'https://www.youtube.com/embed/2oAmBSceuqg',
                'caption' => 'Hyundai Santa Fe 2024 | First Drive | Otodriver',
            ],
            'specs'      => [
                'Bensin dan listrik (untuk varian Plug-in Hybrid / PHEV)',
                '261 hp (untuk mesin bensin dan motor listrik pada varian PHEV)',
                '5.500 RPM (untuk mesin bensin)',
                '1.6 liter (1.598 cc) Turbocharged, 4-silinder',
                '350 Nm',
                '1.500-4.500 RPM (untuk mesin bensin)',
                'Sekitar 1.030 liter (dengan baris ketiga dilipat)',
                '1.025 mm',
                '1.001 mm',
                '1.045 mm',
                '1.900-2.050 kg (tergantung varian)',
                '4.785 mm',
                '1.710 mm',
                '5 pintu',
                '67 liter',
                '2.550-2.650 kg (tergantung varian)',
                '1.900 mm',
                '2.765 mm',
                '7 penumpang',
                '6-speed Automatic Transmission (untuk varian Plug-in Hybrid / PHEV)',
                'All-Wheel Drive (AWD), dengan opsi Front-Wheel Drive (FWD) pada beberapa varian',
                '6-percepatan otomatis',
                'Ya',
                'Ventilated Disc Brakes',
                'MacPherson Strut dengan coil spring dan stabilizer',
                'Solid Disc Brakes',
                'Multi-link dengan coil spring',
                '1.6L Turbocharged Plug-in Hybrid (PHEV)',
                'Direct Injection (Injeksi Langsung)',
                '4 silinder segaris',
                '4 katup per silinder (Total 16 katup dengan teknologi DOHC)',
                'Lithium-ion Polymer Battery',
                'Yes',
                'Permanent Magnet Synchronous Motor (PMSM)',
                '13.8 kWh',
                '3.5 jam menggunakan Level 2 charger (240V)',
                '30-50 g/km PHEV',
                'Ya',
                '19 Inch',
                'All-season tires',
                'Tidak',
                '235/55 R19 dan 245/45 R20 (tergantung varian)',
                'Tersedia dalam dua pilihan, 19 inci dan 20 inci',
                'Ya',
                'Tilt dan Telescopic Adjustment',
                'Tilt dan Telescopic',
                'Rack and Pinion',
                'Rack-and-Pinion dengan sistem Electric Power Assisted Steering (EPAS).',
            ],
        ],

        'palisade' => [
            'name'       => 'HYUNDAI PALISADE',
            'title'      => 'HYUNDAI PALISADE - Dealer Hyundai Makassar',
            'slug'       => 'palisade',
            'price'      => 'Rp910.000.000',
            'image'      => 'images/car/Hyundai-Palisade.png',
            'categories' => ['suv'],
            'folder'     => 'hyundai-palisade',
            'slides'     => 4,
            'benefit'    => 'Keuntungan membeli PALISADE di Hyundai Makassar',
            'brochure'   => 'HYUNDAI PALISADE',
            'video'      => [
                'heading' => 'Video HYUNDAI PALISADE',
                'url'     => 'https://www.youtube.com/embed/6mecS35YDpg',
                'caption' => 'PALISADE I 2023 Update I Premium Features',
            ],
            'specs'      => [
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
            ],
        ],

        'staria' => [
            'name'       => 'HYUNDAI STARIA',
            'title'      => 'HYUNDAI STARIA - Dealer Hyundai Makassar',
            'slug'       => 'staria',
            'price'      => 'Rp924.000.000',
            'image'      => 'images/car/Hyundai-Staria.png',
            'categories' => ['mpv'],
            'folder'     => 'hyundai-staria',
            'slides'     => 4,
            'benefit'    => 'Keuntungan membeli STARIA di Hyundai Makassar',
            'brochure'   => 'HYUNDAI STARIA',
            'video'      => [
                'heading' => 'Video HYUNDAI STARIA',
                'url'     => 'https://www.youtube.com/embed/jIdpGCdP1Z4',
                'caption' => 'HYUNDAI STARIA Paling Mewah Saat Ini',
            ],
            'specs'      => [
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
            ],
        ],

        'ioniq-6' => [
            'name'       => 'HYUNDAI IONIQ 6',
            'title'      => 'HYUNDAI IONIQ 6 - Dealer Hyundai Makassar',
            'slug'       => 'ioniq-6',
            'price'      => 'Rp1.220.000.000',
            'image'      => 'images/car/Hyundai-IONIQ-6.png',
            'categories' => ['eco'],
            'folder'     => 'ioniq-6',
            'slides'     => 1,
            'benefit'    => 'Keuntungan membeli HYUNDAI IONIQ 6 di Hyundai Makassar',
            'brochure'   => 'HYUNDAI IONIQ 6',
            'video'      => [
                'heading' => 'Video HYUNDAI IONIQ 6',
                'url'     => 'https://www.youtube.com/embed/GVcXwIL9OFw',
                'caption' => 'IONIQ 6 | Digital World Premiere',
            ],
            'specs'      => [
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                'Lithium-ion',
                'YES',
                'Permanent Magnet Synchronous Motor',
                '77.4 lWh',
                '(10 to 100%) In 11 Hours 45 Minutes With 7kW & 7 Hours 20 Minutes With 10.5kW Charger',
                '0g/km',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
            ],
        ],

    ],

];
